### ISSUE TITLE
is it really trained on  CIFAR100?

### ISSUE THREAD

**Issue by zzw1123** [monty0157/CNN_CIFAR100#1]
HELLO, i am reading your codes about the cnn on cifar dataset ,but i found that the n_classes=10,so i wonder if it is a classification code on cifar10 dataset instead of cifar100?
thanks!

**Comment by monty0157** [comment]
Hello and sorry, you're absolutely right. It is training on the cifar 10 dataset, and not cifar 100. I will update the title to reflect the true dataset
